# Part1

## 123

In [1]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.datasets import load_iris
import numpy as np
import matplotlib.pyplot as plt
import math
iris_dataset = load_iris()
data = iris_dataset['data']
target = iris_dataset['target'] 

X_train = np.array(data)   
y_train = np.array(target)


In [2]:
def My_KNN(X_train,y_train,k,test,current_list):#K is a random value but can only be an odd number to facilitate judgement
    distances=[]
    #for loop to find the distance between the test data and each point of the training set
    for x_train in X_train:
        d = math.sqrt(np.sum((x_train[0]-X_test[0])**2+(x_train[1]-X_test[1])**2))
        distances.append(d)
    nearest = np.argsort(distances) # return index after sorting from smallest to largest
    near_y = [y_train[i] for i in nearest[:k]]
    for vote in near_y: #for loop to select the y value with the most occurrences in the array
        a=0
        b=0
        c=0
        vote_out = 0
        if vote == 0:
            a+=1
        elif vote == 1:
            b+=1
        else:
            c+=1
        if b>(c or a):
            vote_out = 1
        elif c>( b or a):
            vote_out = 2
        else:
            vote_out = 0

    if vote_out == y_train[test]:
        current_list.append(1)
    else:
        current_list.append(0)
    #print(vote_out,y_train[test])

In [3]:
#Calculate the accurate
current_list=[]
count = 0
k = 5
test = 0
for i in range(data.shape[0]):
    X_test = iris_dataset['data'][test]
    My_KNN(X_train,y_train,k,test,current_list)
    count+=1
    test +=1
current_list
percent = sum(current_list)/len(current_list) #因为数组内只有0和1 所以数组内元素相加/数组长度就是正确率
print("""
In a sample of {0} sets of data, K is {1} and the accuracy of its algorithm prediction is {2}
""".format(count,k,percent))


In a sample of 150 sets of data, K is 5 and the accuracy of its algorithm prediction is 0.7333333333333333



## 5

In [4]:
for k in range(1,10):
    current_list=[]
    count = 0
    test = 0
    for i in range(data.shape[0]):
        X_test = iris_dataset['data'][test]
        My_KNN(X_train,y_train,k,test,current_list)
        count+=1
        test +=1
        current_list
        percent = sum(current_list)/len(current_list) #因为数组内只有0和1 所以数组内元素相加/数组长度就是正确率
    print("""
    In a sample of {0} sets of data, K is {1} and the accuracy of its algorithm prediction is {2}
    """.format(count,k,percent))


    In a sample of 150 sets of data, K is 1 and the accuracy of its algorithm prediction is 0.92
    

    In a sample of 150 sets of data, K is 2 and the accuracy of its algorithm prediction is 0.7733333333333333
    

    In a sample of 150 sets of data, K is 3 and the accuracy of its algorithm prediction is 0.74
    

    In a sample of 150 sets of data, K is 4 and the accuracy of its algorithm prediction is 0.7333333333333333
    

    In a sample of 150 sets of data, K is 5 and the accuracy of its algorithm prediction is 0.7333333333333333
    

    In a sample of 150 sets of data, K is 6 and the accuracy of its algorithm prediction is 0.7266666666666667
    

    In a sample of 150 sets of data, K is 7 and the accuracy of its algorithm prediction is 0.72
    

    In a sample of 150 sets of data, K is 8 and the accuracy of its algorithm prediction is 0.7466666666666667
    

    In a sample of 150 sets of data, K is 9 and the accuracy of its algorithm prediction is 0.68
    


## 4

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train,y_train)

y_pred= neigh.predict(X_test)
#y_pred   
y_all=y_pred-y_test
c=np.sum(y_all == 0)
print("the accuracy of KNN from sklearn is %s",c/len(X_test))

the accuracy of KNN from sklearn is %s 0.98


# Part2

In [6]:
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
#SVM 
#NB
#DT
#prediction
#confusion matrix

In [7]:
data_train,data_test,target_train,target_test=train_test_split(data,target,test_size=0.3,random_state=0)

## SVM

In [8]:
svm=SVC(kernel='rbf',gamma=0.1,decision_function_shape='ovo',C=0.8)#搭建模型，训练SVM分类器
svm.fit(data_train,target_train)#训练SVC
accurate_Svm=svm.score(data_test,target_test)
y_pred = svm.predict(data_test)
print('SVM accuracy is：',accurate_Svm)

confusion_matrix(target_test,y_pred)


SVM accuracy is： 0.9777777777777777


array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [9]:
print("There were 16 predictions in category 1 that were correct.\n")
print('''There were 17 predictions in category 2 that were correct. 1 predicted wrong, it predicted category 2 and actually category 3"
     ''')
print("There were 11 predictions in category 3 that were correct.")

There were 16 predictions in category 1 that were correct.

There were 17 predictions in category 2 that were correct. 1 predicted wrong, it predicted category 2 and actually category 3"
     
There were 11 predictions in category 3 that were correct.


## NB

In [10]:
nb=GaussianNB()
nb.fit(data_train,target_train)
accurate_Nb=nb.score(data_test,target_test)
nb.predict(data_test)
y_pred = nb.predict(data_test)
print('NB accuracy is：',accurate_Nb)

confusion_matrix(target_test,y_pred)

NB accuracy is： 1.0


array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]], dtype=int64)

In [11]:
print("There were 16 predictions in category 1 that were correct.\n")
print('''There were 18 predictions in category 2 that were correct\n ''')
print("There were 11 predictions in category 3 that were correct.")

There were 16 predictions in category 1 that were correct.

There were 18 predictions in category 2 that were correct
 
There were 11 predictions in category 3 that were correct.


## DT

In [12]:
iris = load_iris()
DT = tree.DecisionTreeClassifier(max_depth=4)
DT = DT.fit(data_train,target_train)
accurate_DT = DT.score(data_test,target_test)
y_pred = DT.predict(data_test)
print('DT accuracy is：',accurate_DT)
confusion_matrix(target_test,y_pred)

DT accuracy is： 0.9777777777777777


array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [13]:
print("There were 16 predictions in category 1 that were correct.\n")
print('''There were 17 predictions in category 2 that were correct. 1 predicted wrong, it predicted category 2 and actually category 3"
     ''')
print("There were 11 predictions in category 3 that were correct.")

There were 16 predictions in category 1 that were correct.

There were 17 predictions in category 2 that were correct. 1 predicted wrong, it predicted category 2 and actually category 3"
     
There were 11 predictions in category 3 that were correct.
